language: go

go:
  - 1.x

os:
  - linux

dist: xenial

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

services:
  - docker

sudo: true

before_install:
  - docker --version
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

addons:
  apt:
    update: true
    packages:
      - docker-ce

env:
 global:
   - GO111MODULE=on

script:
  - ./ci/travis.gofmt.sh
  - ./ci/travis.govet.sh
  - go test -v -covermode=count -coverprofile=coverage.out
  - make clean all

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

#before_deploy:
#- make clean all -j2

deploy:
  - provider: releases
    api_key:
      secure: $GITHUB_TOKEN
    file: build/*
    file_glob: true
    skip_cleanup: true
    draft: true
    on:
      tags: true
  - provider: script
    script: ci/deploy-docker.sh
    skip_cleanup: true
    on:
      all_branches: true

notifications:
  email: false
